# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Rating',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
